### ISSUE TITLE
local_node.sh failed for exocored config error 

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#121]
## Summary of Bug

https://github.com/ExocoreNetwork/exocore/pull/109

## Steps to Reproduce

Test object: https://github.com/ExocoreNetwork/exocore/pull/109
```
make build
cp build/exocored to system exocored directory.
`run ./local_node.sh `
```
or directly run the command
`exocored config --keyring-backend test --home /root/.tmp-exocored`

## Screenshots

```
An existing folder at '/root/.tmp-exocored' was found. You can choose to delete this folder and start a new local node with new keys from genesis. When declined, the existing local node is started. 
Overwrite the existing configuration and start a new local node? [y/n]
y
Error: failed to parse /root/.tmp-exocored/config/app.toml: '' expected a map, got 'interface'
Usage:
  exocored config <key> [value] [flags]
```

## Additional context

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MaxMustermann2** [comment]
Closed by #124
