### ISSUE TITLE
Object does not exist at path “/”

### ISSUE THREAD

**Issue by RealLau** [ExocoreNetwork/exocore#13]
## Summary of Bug
got error `Object does not exist at path “/”` when `make localnet-init`

## Version
- ubuntu 22.04
- user: root
- golang: 1.21.0
- make: GNU Make 4.3
- docker: Docker version 25.0.4 with docker compose plugin(v2)
- branch: main

## Steps to Reproduce
- just install all the required packages above and clone the main branch
- `go mod download`
- `cd cmd/exocored && go build .`, an executable binary named **exocored** should generated at current dir
- move that **exocored**  to the root dir of the current repo: `mv exocored ../../` 
- change `docker-compose` to `docker compose` cause I'm using plugin v2
- `make localnet-init`
then you should see the one line output error info.

## Screenshots
![image](https://github.com/ExocoreNetwork/exocore/assets/16678624/5339e9c5-389b-4713-a669-02c525c74b5b)

any suggestion? help

## Additional context
I tried add args with `--log_level trace`, still got no further information.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MaxMustermann2** [comment]
Please provide the value of `pwd` and try running this from the `develop` branch as well. If you cannot run from the develop branch for whatever reason, change the `--keyring-backend` from `os` to `file`.

**Comment by RealLau** [comment]
> Please provide the value of `pwd` and try running this from the `develop` branch as well. If you cannot run from the develop branch for whatever reason, change the `--keyring-backend` from `os` to `file`.

Thanks a lot for ur help, problem solved! 

by the way, what is the ip address `--starting-ip-address 192.168.10.2` stands for in the Makefile in the root dir of the repo? should I change it along with my own host LAN ip when building image?  Much appreciated in advance:)

**Comment by MaxMustermann2** [comment]
> > Please provide the value of `pwd` and try running this from the `develop` branch as well. If you cannot run from the develop branch for whatever reason, change the `--keyring-backend` from `os` to `file`.
> 
> Thanks a lot for ur help, problem solved!
> 
> by the way, what is the ip address `--starting-ip-address 192.168.10.2` stands for in the Makefile in the root dir of the repo? should I change it along with my own host LAN ip when building image? Much appreciated in advance:)

Sorry, one thing to clarify is that instead of `file` you should use `test`. It is much easier to deal with.

The starting IP address is used for the Docker network used by localnet (`make localnet-start`). You should not change it unless it conflicts with your LAN IP. If you do change it, you will have to make similar changes in `docker-compose.yml` as well. It is not used when building the image; it is only used when running the config.
