### ISSUE TITLE
No Check for duplicate token in oracle params

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#138]
## Version

develop(https://github.com/ExocoreNetwork/exocore/commit/2b00dd8bd3ea9298c984e3c0fc5b66d8286204c6)  + PR #132(https://github.com/ExocoreNetwork/exocore/pull/132/commits/de82413a93830b650a1eca8a699e00244119d4e9)  + PR #133(https://github.com/ExocoreNetwork/exocore/pull/133/commits/42837d9a7e4b202a62e3260aec43125401f7fd5b) + PR #136 https://github.com/ExocoreNetwork/exocore/pull/136/commits/f894ccf673548985aafcb9f4621b6d6749158348

## Steps to Reproduce

![photo_2024-07-19_09-48-29](https://github.com/user-attachments/assets/13b30370-beec-4ea4-878c-a9950bb26c14)

## Screenshots

`exocored validate-genesis --home /root/.test-oracle`   
No error shows.

## Additional context

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by leonz789** [comment]
resolved
