### ISSUE TITLE
Docker file build failed

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#36]
branch: develop  commit: 91af9dbf9d72aaede8691e5a97ef12ce21e3e735
os: Ubuntu 20.04.4 LTS

Reproduce steps:

1. make localnet-init
2. make localnet-build

![image](https://github.com/ExocoreNetwork/exocore/assets/34291844/87179a73-a0bf-41af-adb8-415965c321a3)

![image](https://github.com/ExocoreNetwork/exocore/assets/34291844/4962481e-1265-4c8b-ab53-28a27f5fd706)

**Comment by MaxMustermann2** [comment]
Closed by #37
