### ISSUE TITLE
Panic in `ContextForHistoricalState` when slashing

### ISSUE THREAD

**Issue by MaxMustermann2** [ExocoreNetwork/exocore#44]
## Summary of Bug

When a downtime slashing event occurs, it is cascaded from `x/staking` to `x/dogfood`  to `x/operator` to `x/assets`. The last of these modules attempts to fetch the state, as of the slashing event height, to determine which (and how many) assets were staked then. These assets are liable to be slashed.

## Version

602abe171bf85aa160511134851d3177cc211f39 from #42 

## Steps to Reproduce

- Create a localnet of N nodes
- Start the network and wait for blocks to be produced
- Take down one of the nodes, keeping N-1 running
- Wait for the Nth node to be slashed (~50 blocks)

## Logs

```go
ERR CONSENSUS FAILURE!!! err="cannot get latest version from branch cached multi-store" module=consensus server=node stack="goroutine 183 [running]:
runtime/debug.Stack()
  runtime/debug/stack.go:24 +0x5e
github.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()
  github.com/cometbft/cometbft@v0.37.2/consensus/state.go:732 +0x46
panic({0x2b51c40?, 0x4001a40?})
  runtime/panic.go:914 +0x21f
github.com/cosmos/cosmos-sdk/store/cachemulti.Store.LatestVersion(...)
  github.com/cosmos/cosmos-sdk@v0.47.5/store/cachemulti/store.go:114
github.com/ExocoreNetwork/exocore/x/assets/types.ContextForHistoricalState({{0x403ce48, 0x5e6b580}, {0x40579f0, 0xc0074aa140}, {{0xb, 0x0}, {0xc005df4600, 0x14}, 0x35a866, {0x24b68c41, ...}, ...}, ...}, ...)
  github.com/ExocoreNetwork/exocore/x/assets/types/general.go:167 +0xb9
github.com/ExocoreNetwork/exocore/x/operator/keeper.(*Keeper).Slash(_, {{0x403ce48, 0x5e6b580}, {0x40579f0, 0xc0074aa140}, {{0xb, 0x0}, {0xc005df4600, 0x14}, 0x35a866, ...}, ...}, ...)
  github.com/ExocoreNetwork/exocore/x/operator/keeper/slash.go:196 +0x105
    github.com/ExocoreNetwork/exocore/x/operator/keeper.Keeper.SlashWithInfractionReason({{0x4016550, 0xc0019c4ef0}, {0x40572e0, 0xc001789060}, {0x40452f8, 0xc0007ad420}, {0x403cf98, 0xc0014973d0}, {0x40165a0, 0x5e6b580}, ...}, ...)
  github.com/ExocoreNetwork/exocore/x/operator/keeper/slash.go:259 +0x445
    github.com/ExocoreNetwork/exocore/x/dogfood/keeper.Keeper.SlashWithInfractionReason({{0x40572e0, 0xc001789060}, {0x4016550, 0xc0019c4d60}, {{0x40572e0, 0xc001789060}, 0xc000d0a118, {0x4016550, 0xc0019c4d90}, {0x4016578, ...}, ...}, ...}, ...)
  github.com/ExocoreNetwork/exocore/x/dogfood/keeper/impl_sdk.go:104 +0x138
    github.com/cosmos/cosmos-sdk/x/slashing/keeper.Keeper.HandleValidatorSignature({{_, _}, {_, _}, _, {_, _}, {_, _}}, {{0x403ce48, ...}, ...}, ...)
```

**Comment by TimmyExogenous** [comment]
https://github.com/TimmyExogenous/exocore/commit/2ddfbcec5d8a4ac90803959363f749f6aa1356fa#diff-c7dac2a33f2c16933d80f06a30c8eab2a5a004528045ea6316831d6b4c6cc5dfR17
The above commit might fix this bug. It will use the `CreateQueryContext` from `BaseApp`.
Given the current mechanism of voting power and slash is an old version, I might submit a PR to disable the slash currently.
Then the fixed code is going to be submitted by a new PR after the #39.

**Comment by TimmyExogenous** [comment]
It seems like the slash has been disabled; it's odd if the issue still exists.
