### ISSUE TITLE
Missing `ExportGenesis` implementations

### ISSUE THREAD

**Issue by MaxMustermann2** [ExocoreNetwork/exocore#54]
- [ ] x/assets
- [ ] x/avs
- [ ] x/delegation
- [x] x/dogfood
- [x] x/oracle (not fully implemented yet AFAIK)
- [ ] x/operator
- [ ] x/reward
- [ ] x/slash

Tracking issue for missing `ExportGenesis` or `ImportGenesis` implementations. Feel free to remove or mark as done if it doesn't apply to your module.

**Comment by leonz789** [comment]
#206
