### ISSUE TITLE
Voting Power not Updating Correctly After Two Epoch for New Registered Operator

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#79]
## Summary of Bug

After a new operator registered, and has some delegation, voting power of the operators update for the first time, but in the next epoch, the new operators voting power record is missing.

## Steps to Reproduce

1. Start 3 cluster nodes,  with delegates 3000,2000,1000 for each operator, say `operator1`, `operator2`, `operator3`.
2. Delegate 2 * e18 to `operator1`, delegate 1 * e18 to `operator3`. (this step is aiming to verify deposit and delegate work flow)
3. Register a new operator say `jessica1` , and a new depositor deposit 2*e18 token, delegate 2*e18 token to `jessica1`.
4. Wait for the next epoch. here epoch is **day**.  (epoch 3 in the context)
5. Check the voting power at the latest height, and it is correct, and have four operator records.
6. Delegate 3000 *e18 to `jessica1`
7. Wait for the next epoch, check the voting power at the latest height.  (epoch 4)
8. There are only three operator records. 

## Screenshots

At the 3rd epoch, voting power update with correct data. Height: **3988362**

```shell
- current_epoch: "3"
  current_epoch_start_height: "3988359"
  current_epoch_start_time: "2024-05-29T08:46:00Z"
  duration: "86400000000000"
  epoch_counting_started: true
  identifier: day
  start_time: "2024-05-27T08:46:00Z"
- current_epoch: "1"
  current_epoch_start_height: "3939076"
  current_epoch_start_time: "2024-05-27T08:46:00Z"
  duration: "604800000000000"
  epoch_counting_started: true
  identifier: week
  start_time: "2024-05-27T08:46:00Z"
pagination:
  total: "2"
```

```shell
curl --request GET --url 'http://localhost:20000/validators?height=3988362&page
=1&per_page=30' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   918  100   918    0     0   896k      0 --:--:-- --:--:-- --:--:--  896k
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "block_height": "3988362",
    "validators": [
      {
        "address": "46B029E2D285423E4288C434D1AC727B8C9B97DE",
        "pub_key": {
          "type": "tendermint/PubKeyEd25519",
          "value": "TJ3pTh8yJZBmAq6BLjDxvlZCcSbWDy9stmG39P2mONw="
        },
        "voting_power": "3002",
        "proposer_priority": "2798"
      },
      {
        "address": "4FFE906A72A2F05770FD3A9AB034FD324CCED4EE",
        "pub_key": {
          "type": "tendermint/PubKeyEd25519",
          "value": "XLtFCK0/nB1xExSXEhH5kaxRte3aIXSGaBfWSeNOtpE="
        },
        "voting_power": "2000",
        "proposer_priority": "-525"
      },
      {
        "address": "38A21AA8D3386568C4FC0B041F16B77A9D7F06AB",
        "pub_key": {
          "type": "tendermint/PubKeyEd25519",
          "value": "8PaRnlIsW5fbLIJVv/dD+d/d162fw3ywwWcLSA0PmRQ="
        },
        "voting_power": "1001",
        "proposer_priority": "2791"
      },
      {
        "address": "112F03168B73F54AC20B32277C19D1F0434E2C57",
        "pub_key": {
          "type": "tendermint/PubKeyEd25519",
          "value": "z59Ou7lmwjao17+nRRAF1tcYV7UyvS65WoAMyq2xKbs="
        },
        "voting_power": "2",
        "proposer_priority": "-5062"
      }
    ],
    "count": "4",
    "total": "4"
  }
}
```

After delegate 1000 * e18 tokens to the new registered operator, say `operator4`.  and wait for the 4th epoch.

```shell
epochs:
- current_epoch: "4"
  current_epoch_start_height: "4014294"
  current_epoch_start_time: "2024-05-30T08:46:00Z"
  duration: "86400000000000"
  epoch_counting_started: true
  identifier: day
  start_time: "2024-05-27T08:46:00Z"
- current_epoch: "1"
  current_epoch_start_height: "3939076"
  current_epoch_start_time: "2024-05-27T08:46:00Z"
  duration: "604800000000000"
  epoch_counting_started: true
  identifier: week
  start_time: "2024-05-27T08:46:00Z"
pagination:
  total: "2"
```

```shell
curl --request GET --url 'http://localhost:20000/validators?height=4015065&page=1&per_page=30' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   717  100   717    0     0   700k      0 --:--:-- --:--:-- --:--:--  700k
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "block_height": "4015065",
    "validators": [
      {
        "address": "46B029E2D285423E4288C434D1AC727B8C9B97DE",
        "pub_key": {
          "type": "tendermint/PubKeyEd25519",
          "value": "TJ3pTh8yJZBmAq6BLjDxvlZCcSbWDy9stmG39P2mONw="
        },
        "voting_power": "3002",
        "proposer_priority": "-1188"
      },
      {
        "address": "4FFE906A72A2F05770FD3A9AB034FD324CCED4EE",
        "pub_key": {
          "type": "tendermint/PubKeyEd25519",
          "value": "XLtFCK0/nB1xExSXEhH5kaxRte3aIXSGaBfWSeNOtpE="
        },
        "voting_power": "2000",
        "proposer_priority": "3110"
      },
      {
        "address": "38A21AA8D3386568C4FC0B041F16B77A9D7F06AB",
        "pub_key": {
          "type": "tendermint/PubKeyEd25519",
          "value": "8PaRnlIsW5fbLIJVv/dD+d/d162fw3ywwWcLSA0PmRQ="
        },
        "voting_power": "1001",
        "proposer_priority": "-1920"
      }
    ],
    "count": "3",
    "total": "3"
  }
}
```

## Additional context

All operators and delegation info for each operator.

```shell
operator_acc_addrs:
- exo1rtg0cgw94ep744epyvanc0wdd5kedwql73vlmr
- exo1wnw7zcl9fy04ax69uffumwkdxftfqsjyj37wt2
- exo13hasr43vvq8v44xpzh0l6yuym4kca98f87j7ac
- exo1m4stcmwunt4ufuaz090cluyzjnpf8flc8rypyt
pagination:
  next_key: null
  total: "4"

root@den-sm5038ml-h12trf-6-11:~/Jessica/testscript# exocored q assets QueOperatorAssetInfos exo1m4stcmwunt4ufuaz090cluyzjnpf8flc8rypyt --node http://localhost:20000
asset_infos:
  0x83e6850591425e3c1e263c054f4466838b9bd9e4_0x9ce1:
    operator_amount: "0"
    operator_share: "0.000000000000000000"
    operator_unbonding_amount: "0"
    total_amount: "3002000000000000000000"
    total_share: "3002000000000000000000.000000000000000000"
    wait_unbonding_amount: "0"
root@den-sm5038ml-h12trf-6-11:~/Jessica/testscript# exocored q assets QueOperatorAssetInfos exo1rtg0cgw94ep744epyvanc0wdd5kedwql73vlmr --node http://localhost:20000
asset_infos:
  0x83e6850591425e3c1e263c054f4466838b9bd9e4_0x9ce1:
    operator_amount: "0"
    operator_share: "0.000000000000000000"
    operator_unbonding_amount: "0"
    total_amount: "3002000000000000000000"
    total_share: "3002000000000000000000.000000000000000000"
    wait_unbonding_amount: "0"
root@den-sm5038ml-h12trf-6-11:~/Jessica/testscript# exocored q assets QueOperatorAssetInfos exo1wnw7zcl9fy04ax69uffumwkdxftfqsjyj37wt2 --node http://localhost:20000
asset_infos:
  0x83e6850591425e3c1e263c054f4466838b9bd9e4_0x9ce1:
    operator_amount: "0"
    operator_share: "0.000000000000000000"
    operator_unbonding_amount: "0"
    total_amount: "2000000000000000000000"
    total_share: "2000000000000000000000.000000000000000000"
    wait_unbonding_amount: "0"
root@den-sm5038ml-h12trf-6-11:~/Jessica/testscript# exocored q assets QueOperatorAssetInfos exo13hasr43vvq8v44xpzh0l6yuym4kca98f87j7ac --node http://localhost:20000
asset_infos:
  0x83e6850591425e3c1e263c054f4466838b9bd9e4_0x9ce1:
    operator_amount: "0"
    operator_share: "0.000000000000000000"
    operator_unbonding_amount: "0"
    total_amount: "1001000000000000000000"
    total_share: "1001000000000000000000.000000000000000000"
    wait_unbonding_amount: "0"
```
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cloud8little** [comment]
An easy way to reproduce this issue.

1. Start single node consensus, with local_node.sh is ok, the default voting power for the default validator is 5000.
2. Add sepolia as client chain, add a restake token as assets in exocore.
3. Deploy client chain gateway and layerzero endpoint on sepolia, deploy exocoreGateway endpoint on exocore.
4. Add exocoreGateway address to assets module.
5. Deposit 1000 restake token for an depositor.
6. Register a new operator, say `newOperator1 `  and delegate 1000 to the `newOperator1`. (NOTE: the voting power data was correct here)
7. Deposit 3000 restake token.
8. Register another new operator, say `newOperator2 `and delegate 3000 to the `newOperator2 `
9. check voting power update after epoch, the voting power for `newOperator2 ` is missing.

**Comment by TimmyExogenous** [comment]
The issue wasn't reproduced, the process is as follows:
The version is a customized `V1.0.0' which uses each block as the epoch.
1. Start a single node with `local_node.sh`, the voting power is `5000` and the node works well.
2. Start a new node named `node1` to connect the current node, and wait for all blocks to be synced.
3. Register a new operator named `newOperator1`, then deposit and delegate `1000` to the newOperator1 from the EOA address. 
4. Opt into the `dogfood` module and set the consensus key of `node1` for the `newOperator1`. The voting power in `cometbft` was updated correctly.
5. Deposit and delegate `5000` to the `neOperator1` again, the voting power in `cometbft` was updated to `6000`.
6. Check the generated block information, two validators signed the block.
7. Start another new node named `node2` to connect the current two nodes' network, and wait for all blocks to be synced.
8. Register a new operator named `newOperator2`, then deposit and delegate `50000` to the newOperator2 from the EOA address. 
9. Opt into the `dogfood` module and set the consensus key of `node2` for the `newOperator2`. The voting power in `cometbft` was updated correctly.
10. Check the generated block information, three validators signed the block.
11. Deposit and delegate `50000` to the `neOperator2` again, the voting power in `cometbft` was updated to `100000`.

As for the issue, I have a guess: 
If the node of the new registered operator hasn't been started or synced well before the voting power is enabled.  The node will be slashed by the downtime action, then the related validator information will be removed from the `cometbft`. But this should be an expected result.  The specification documentation should remind the operator of this.

**Comment by cloud8little** [comment]
I've tried three different scenarioes for the new registered operator.

1. Register operator via the consensus nodes, without running the new registered node, and then opt into avs, set cons key. and give some delegations to this operator, after the current epoch ends, the next epoch starts, start the new registered node. 
[**Result**] the voting power for the new registered operator correctly shows.

2. Running the new registered node as a non-validator node, and sync blocks, then register as an operator, opt into avs, set cons key. and give some delegations to this operator, after the current epoch ends, the next epoch starts.
[**Result**]  the voting power for the new registered operator correctly shows.

3.  Running the new registered node as a non-validator node, and sync blocks, then register as an operator, opt into avs, set cons key. and give some delegations to this operator, after the current epoch ends, the next epoch starts. 
The voting power for the new registered operator correctly shows, to test show voting power works, stop the new registered node for a while(normally about 1 minute) and then restart the node.
[**Result**] When next epoch starts, the voting power for the new registered operator is missing. 
Since the configuration for downtime is  `"downtime_jail_duration": "600s"` . It seems unreasonable to slash the node after the node just down for less than 10 minutes.

**Comment by TimmyExogenous** [comment]
The DowntimeJailDuration is the duration a validator is jailed when a downtime action has been detected. In other words, the validator can submit a transaction to unjail itself once this duration expires. Therefore, the result is expected. This test might also verify the guess regarding the issue.

**Comment by cloud8little** [comment]
Close this one since it is not a bug. If any further issue found, will reopen this one.
