### ISSUE TITLE
Exocore binary Decomporess from Release Page not Working

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#84]
## Summary of Bug

Exocore binary in the release page not working on linux system.

## Steps to Reproduce

1. Download https://github.com/ExocoreNetwork/exocore/releases/download/v1.0.0/exocore_1.0.0_Linux_amd64.tar.gz.
2. tar -xvf exocore_1.0.0_Linux_amd64.tar.gz
3. cd bin
4. ./exocored version

```
./exocored version
Caught SIGILL in blst_cgo_init, consult <blst>/bindings/go/README.md.
```

**Comment by MaxMustermann2** [comment]
I can't reproduce this on my laptop. I tried in a new empty Ubuntu Docker container as well (to make sure it wasn't my set up) and I still cannot reproduce it.

**Comment by cloud8little** [comment]
> I can't reproduce this on my laptop. I tried in a new empty Ubuntu Docker container as well (to make sure it wasn't my set up) and I still cannot reproduce it.

It happens only on QA test machine, works on other virtual machines. I guess it is a hardware issue.
