### ISSUE TITLE
[Feature] Access Control for Register Assets, Register Client Chain, Gateway Params

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#90]
## Summary of Bug

For now, **EVERYONE** can register assets, register a client chain, and update the exocore Gateway Params. especially exocore Gateway Params, it is dangerous and can cause the whole system broken. 

But it should be controlled by the multi-signature address of consensus members or exocore system administrator. 

Access control for assets module

- [ ] Register client chain
- [ ] Register assets
- [ ] Update params

**Comment by adu-web3** [comment]
yes, this issue would be alleviated after we implement feature of registering/deregistering assets to/from Exocore from client chain contracts and resolve issue https://github.com/ExocoreNetwork/exocore-contracts/issues/12

**Comment by cloud8little** [comment]
> yes, this issue would be alleviated after we implement feature of registering/deregistering assets to/from Exocore from client chain contracts and resolve issue [ExocoreNetwork/exocore-contracts#12](https://github.com/ExocoreNetwork/exocore-contracts/issues/12)

agree, the most insecure part is the gateway update function, **everyone** can change the exocore Gateway address by updating the asset Params, the client chain gateway will not work then.

**Comment by adu-web3** [comment]
as for the access control for updating params, which is used for registering the canonical ExocoreGateway address, I have talked with @MaxMustermann2 and @TimmyExogenous and might hardcode a special address like `0x00000888` as the canonical address in genesis file, thus avoiding set it afterwards.

The cons are that if we hardcode it in genesis, we can only upgrade it by contract owner and would not be able to redeploy it afterwards unless we have some governance mechanism

@cloud8little what do you think about this? do you think it's acceptable if we can not change this address after we hardcode it in genesis?

**Comment by cloud8little** [comment]
> as for the access control for updating params, which is used for registering the canonical ExocoreGateway address, I have talked with @MaxMustermann2 and @TimmyExogenous and might hardcode a special address like `0x00000888` as the canonical address in genesis file, thus avoiding set it afterwards.
> 
> The cons are that if we hardcode it in genesis, we can only upgrade it by contract owner and would not be able to redeploy it afterwards unless we have some governance mechanism
> 
> @cloud8little what do you think about this? do you think it's acceptable if we can not change this address after we hardcode it in genesis?

looks good to me.

**Comment by MaxMustermann2** [comment]
I have implemented somewhat of a rudimentary fix that requires that only a certain sender sign such transactions. Please see it in #97 and let me know if this approach works for the modules side of things. It should be quick to implement in `x/assets` or any other module for that matter. CC @leonz789 ref #83
